#!/usr/bin/env bash
# ─── SAP Expense Entry System — local dev launcher ───────────────────────────
set -euo pipefail

APP_PORT=8000
MOCK_PORT=50001
DB_PORT=3316        # host port for MySQL (avoid clash with any local 3306)
DB_NAME=expense_app
DB_USER=expense_user
DB_PASS=expense_pass
DB_ROOT_PASS=rootpass
CONTAINER=expense_mysql

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ ok ]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
die()   { echo -e "${RED}[fail]${NC}  $*"; exit 1; }

# ─── 1. Check requirements ────────────────────────────────────────────────────
command -v php    >/dev/null || die "php not found"
command -v docker >/dev/null || die "docker not found"

PHP=$(php --version | head -1)
ok "PHP: $PHP"

# ─── 2. Start MySQL in Docker ─────────────────────────────────────────────────
if docker ps -q --filter "name=^${CONTAINER}$" | grep -q .; then
    ok "MySQL container '${CONTAINER}' already running."
else
    if docker ps -aq --filter "name=^${CONTAINER}$" | grep -q .; then
        info "Starting existing container '${CONTAINER}'…"
        docker start "$CONTAINER" >/dev/null
    else
        info "Creating MySQL 8 container '${CONTAINER}'…"
        docker run -d \
            --name "$CONTAINER" \
            -e MYSQL_ROOT_PASSWORD="$DB_ROOT_PASS" \
            -e MYSQL_DATABASE="$DB_NAME" \
            -e MYSQL_USER="$DB_USER" \
            -e MYSQL_PASSWORD="$DB_PASS" \
            -p "127.0.0.1:${DB_PORT}:3306" \
            mysql:8 \
            --character-set-server=utf8mb4 \
            --collation-server=utf8mb4_unicode_ci \
            >/dev/null
        ok "Container started."
    fi

    info "Waiting for MySQL to be ready (up to 60 s)…"
    for i in $(seq 1 30); do
        if docker exec "$CONTAINER" mysqladmin ping -u root -p"$DB_ROOT_PASS" --silent 2>/dev/null; then
            ok "MySQL is ready."; break
        fi
        [ "$i" -eq 30 ] && die "MySQL did not start in time."
        sleep 2
    done
fi

# ─── 3. Apply schema ──────────────────────────────────────────────────────────
info "Applying database schema…"
docker exec -i "$CONTAINER" \
    mysql -u root -p"$DB_ROOT_PASS" "$DB_NAME" < db/schema.sql 2>/dev/null \
    && ok "Schema applied." \
    || warn "Schema already exists (or error — check db/schema.sql)."

# ─── 4. Write config env ──────────────────────────────────────────────────────
cat > config/.env.local <<EOF
# Auto-generated by start.sh — do not commit
SAP_BASE_URL=http://localhost:${MOCK_PORT}/b1s/v1
SAP_COMPANY_DB=MOCK_COMPANY
SAP_USERNAME=manager
SAP_PASSWORD=manager
SAP_VERIFY_SSL=false
DB_HOST=127.0.0.1
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASS}
APP_CURRENCY=EUR
APP_VAT_RATE=19
APP_COMPANY=Demo Company
EOF
ok "Config written to config/.env.local"

# ─── 5. Load env into shell & PHP ─────────────────────────────────────────────
set -o allexport
# shellcheck disable=SC1091
source config/.env.local
set +o allexport

# ─── 6. Start SAP mock server ─────────────────────────────────────────────────
if lsof -ti ":${MOCK_PORT}" >/dev/null 2>&1; then
    warn "Port ${MOCK_PORT} already in use — assuming mock already running."
else
    info "Starting SAP B1 mock on http://localhost:${MOCK_PORT} …"
    php -S "localhost:${MOCK_PORT}" mock/sap_mock.php \
        >"${TMPDIR:-/tmp}/sap_mock.log" 2>&1 &
    MOCK_PID=$!
    sleep 1
    kill -0 "$MOCK_PID" 2>/dev/null && ok "SAP mock PID $MOCK_PID" \
        || die "SAP mock failed to start. Check ${TMPDIR:-/tmp}/sap_mock.log"
fi

# ─── 7. Start PHP dev server ──────────────────────────────────────────────────
if lsof -ti ":${APP_PORT}" >/dev/null 2>&1; then
    warn "Port ${APP_PORT} already in use — assuming app already running."
else
    info "Starting PHP dev server on http://localhost:${APP_PORT} …"
    # Export env vars for PHP built-in server child process
    export SAP_BASE_URL SAP_COMPANY_DB SAP_USERNAME SAP_PASSWORD SAP_VERIFY_SSL
    export DB_HOST DB_NAME DB_USER DB_PASSWORD
    export APP_CURRENCY APP_VAT_RATE APP_COMPANY
fi

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Expense Entry System is ready!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  App URL   :  ${CYAN}http://localhost:${APP_PORT}${NC}"
echo -e "  SAP mock  :  http://localhost:${MOCK_PORT}/b1s/v1"
echo -e "  MySQL     :  127.0.0.1:${DB_PORT}  (user: ${DB_USER} / ${DB_PASS})"
echo ""
echo -e "  Press ${YELLOW}Ctrl+C${NC} to stop the app server."
echo ""

# Run app server in foreground so Ctrl+C stops everything cleanly
trap 'echo ""; info "Shutting down…"; kill $(lsof -ti :'"${MOCK_PORT}"') 2>/dev/null; exit 0' INT

php -S "localhost:${APP_PORT}" -t . router.php
